version: '3'
services:
  reacts:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
#  celery:
#    build: .
#    command: celery worker -l info -A snakeeyes.blueprints.contact.tasks